version: '3.9'

services:
  backend:
    build: ../backend
    ports:
      - "8000:8000"
    volumes:
      - ../data:/app/data
    environment:
      - DATABASE_URL=sqlite:///../data/database.db

  frontend:
    build: ../frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend
