name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install Dependencies
      working-directory: backend
      run: |
        pip install -r requirements.txt
    - name: Run Backend Tests
      working-directory: backend
      run: |
        pytest tests/

  frontend-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Install dependencies
      working-directory: frontend
      run: npm install
    - name: Run Frontend Tests
      working-directory: frontend
      run: npm test
